[project]
name = "pydantic-ai-tryout"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jettro Coenradie", email = "jettro@coenradie.com" }
]
requires-python = ">=3.12"
dependencies = [
    "logfire[system-metrics]>=4.40.0",
    "pydantic-ai-slim[logfire,openai]>=2.32.1",
    "python-dotenv>=1.2.3",
]

[project.scripts]
pydantic-ai-tryout = "pydantic_ai_tryout:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
